# This is a simple deployment example for bosh-lite.
#
# Check README for further instructions for deployment

---
name: jenkins_master
director_uuid: <%= `bosh status | grep UUID | awk '{print $2}'` %>

releases:
- name: jenkins-release-dev
  version: latest

networks:
- name: default
  subnets:
  - range: 10.245.0.0/28
    reserved: [10.245.0.1]
    static: [10.245.0.2,10.245.0.6,10.245.0.10]
    cloud_properties:
      name: random

compilation:
  workers: 2
  network: default
  cloud_properties: {}

update:
  canaries: 1
  canary_watch_time: 60000
  update_watch_time: 60000
  max_in_flight: 2

properties:
  jenkins:
    admin:
      password: jEnKins

resource_pools:
- name: warden
  network: default
  size: 1
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest
  cloud_properties: {}

jobs:
- name: jenkins_master
  templates:
  - name: jenkins_master
  instances: 1
  resource_pool: warden
  networks:
  - name: default
    static_ips:
    - 10.245.0.2
  properties: {}